steps:
  # Install NPM modules
  - id: "install"
    name: node:12.19.0
    entrypoint: yarn
    args: ["install"]
  - id: "build"
    name: 'gcr.io/cloud-builders/yarn'
    args: ['build-develop']
  - name: gcr.io/$PROJECT_ID/firebase
    args: ['deploy', '--project=$PROJECT_ID', '--only=hosting:dev-nodocs-app']
