steps:
  # Install NPM modules
  - id: "install"
    name: node:12.19.0
    entrypoint: yarn
    args: ["install"]
  - id: "build"
    name: 'gcr.io/cloud-builders/yarn'
    args: ['build-develop']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-d', '-r', 'build/','gs://dev.nodocs.app']
