export const PUT_TEAMS = 'team/PUT_TEAMS'
export const INITIALIZE_TEAM = 'team/INITIALIZE_TEAM'
export const SET_ACTIVE_TEAM = 'team/SET_ACTIVE_TEAM'
export const CREATE_TEAM = 'team/CREATE_TEAM'
export const CREATE_COLLECTION = 'collection/CREATE_COLLECTION'
export const ADD_MEMBERS = 'member/ADD_MEMBERS'
