export const PUT_DOCUMENTS = 'document/PUT_DOCUMENTS'
export const CREATE_DOCUMENT = 'document/CREATE_DOCUMENT'
export const INITIALIZE_DOCUMENT = 'document/INITIALIZE_DOCUMENT'
export const CREATE_SECTION = 'document/CREATE_SECTION'
export const SWITCH_SECTION = 'document/SWITCH_SECTION'
export const CLEAR_DOCUMENT = 'documents/CLEAR_DOCUMENT'
