export const SET_ACTIVE_PAGE_ID = 'document/SET_ACTIVE_PAGE_ID'
export const SET_ACTIVE_SECTION_ID = 'document/SET_ACTIVE_SECTION_ID'
export const SET_ACTIVE_DOCUMENT_ID = 'document/SET_ACTIVE_DOCUMENT_ID'
